defaults.url=https://sentry.io/
defaults.org=university-of-kansas
defaults.project=strabospot-2
auth.token=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